name: Testing DOtnet environment 

on:
  push:
    branches: ['sprint**','release/**']
    

jobs:
  prints:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      name: dotnet installation
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          5.x
          3.1.x
      name: validation
    - run: |
        cd C:\Users\runneradmin\AppData\Local\Microsoft\dotnet\
        dir
        dotnet --version
        
